name: Deploy Vue.js app to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Instale as dependências no diretório do projeto Vue.js
      - name: Install dependencies
        run: |
          cd Website 
          npm install

      # Faça o build do projeto no diretório do Vue.js
      - name: Build the project
        run: |
          cd Website 
=======
      # Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # Navegue até o diretório "Website" e instale dependências
      - name: Install dependencies
        run: |
          cd Website
          npm install

      # Faça o build do projeto Vue.js no diretório "Website"
      - name: Build the project
        run: |
          cd Website
>>>>>>> 1b247ce52a5eded9ef66c1a0e790e9a56b734e3a
          npm run build

      # Envie os artefatos de build para o GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
<<<<<<< HEAD
          path: './Website/dist' # Atualize o caminho para o diretório de build

      # Deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
=======
          path: './Website/dist'

      # Deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
>>>>>>> 1b247ce52a5eded9ef66c1a0e790e9a56b734e3a
